#include "datastructures.h"
#include "utils.h" // for getDisplayName
#include "defines.h"
#include "browser.h"

// --- Array Implementation ---

Array* Array_new(void) {
    Array* self = malloc(sizeof(Array));
    self->count = 0;
    self->capacity = 8;
    self->items = malloc(sizeof(void*) * self->capacity);
    return self;
}

void Array_push(Array* self, void* item) {
    if (self->count >= self->capacity) {
        self->capacity *= 2;
        self->items = realloc(self->items, sizeof(void*) * self->capacity);
    }
    self->items[self->count++] = item;
}

void Array_unshift(Array* self, void* item) {
    if (self->count == 0) return Array_push(self, item);
    Array_push(self, NULL); // ensures we have enough capacity
    for (int i = self->count - 2; i >= 0; i--) {
        self->items[i + 1] = self->items[i];
    }
    self->items[0] = item;
}

void* Array_pop(Array* self) {
    if (self->count == 0) return NULL;
    return self->items[--self->count];
}

void Array_remove(Array* self, void* item) {
	if (self->count==0 || item == NULL)
		return;
	int i = 0;
	while (self->items[i] != item) i++;
	for (int j = i; j < self->count-1; j++)
		self->items[j] = self->items[j+1];
	self->count--;
}

void Array_reverse(Array* self) {
    int end = self->count - 1;
    int mid = self->count / 2;
    for (int i = 0; i < mid; i++) {
        void* item = self->items[i];
        self->items[i] = self->items[end - i];
        self->items[end - i] = item;
    }
}

void Array_free(Array* self) {
    free(self->items);
    free(self);
}

void Array_yoink(Array* self, Array* other) {
    for (int i = 0; i < other->count; i++)
        Array_push(self, other->items[i]);
    Array_free(other);
}

int StringArray_indexOf(Array* self, char* str) {
    for (int i = 0; i < self->count; i++) {
        if (exactMatch(self->items[i], str)) return i;
    }
    return -1;
}

void StringArray_free(Array* self) {
    for (int i = 0; i < self->count; i++) {
        free(self->items[i]);
    }
    Array_free(self);
}

// --- Hash Implementation ---

Hash* Hash_new(void) {
    Hash* self = malloc(sizeof(Hash));
    self->keys = Array_new();
    self->values = Array_new();
    return self;
}

void Hash_free(Hash* self) {
    StringArray_free(self->keys);
    StringArray_free(self->values);
    free(self);
}

void Hash_set(Hash* self, char* key, char* value) {
    Array_push(self->keys, strdup(key));
    Array_push(self->values, strdup(value));
}

char* Hash_get(Hash* self, char* key) {
    int i = StringArray_indexOf(self->keys, key);
    if (i == -1) return NULL;
    return self->values->items[i];
}

// --- Entry Implementation ---

Entry* Entry_new(char* path, int type) {
    char display_name[256];
    getDisplayName(path, display_name);
    Entry* self = malloc(sizeof(Entry));
    self->path = strdup(path);
    self->name = strdup(display_name);
    self->unique = NULL;
    self->type = type;
    self->alpha = 0;
    return self;
}

Entry* Entry_newNamed(char* path, int type, char* displayName) {
	Entry *self = Entry_new(path, type);
    free(self->name); // free the name generated by Entry_new
	self->name = strdup(displayName);
	return self;
}

void Entry_free(Entry* self) {
    free(self->path);
    free(self->name);
    if (self->unique) free(self->unique);
    free(self);
}

int EntryArray_indexOf(Array* self, char* path) {
    for (int i = 0; i < self->count; i++) {
        Entry* entry = self->items[i];
        if (exactMatch(entry->path, path)) return i;
    }
    return -1;
}

static int EntryArray_sortEntry(const void* a, const void* b) {
    Entry* item1 = *(Entry**)a;
    Entry* item2 = *(Entry**)b;
    return strcasecmp(item1->name, item2->name);
}

void EntryArray_sort(Array* self) {
    qsort(self->items, self->count, sizeof(void*), EntryArray_sortEntry);
}

void EntryArray_free(Array* self) {
    for (int i = 0; i < self->count; i++) {
        Entry_free(self->items[i]);
    }
    Array_free(self);
}

// --- IntArray Implementation ---

IntArray* IntArray_new(void) {
    IntArray* self = malloc(sizeof(IntArray));
    self->count = 0;
    memset(self->items, 0, sizeof(int) * INT_ARRAY_MAX);
    return self;
}

void IntArray_push(IntArray* self, int i) {
    if (self->count < INT_ARRAY_MAX) {
        self->items[self->count++] = i;
    }
}

void IntArray_free(IntArray* self) {
    free(self);
}

// --- Directory Implementation ---

void Directory_free(Directory* self) {
    free(self->path);
    free(self->name);
    EntryArray_free(self->entries);
    IntArray_free(self->alphas);
    free(self);
}

void DirectoryArray_pop(Array* self) {
    Directory_free(Array_pop(self));
}

void DirectoryArray_free(Array* self) {
    for (int i = 0; i < self->count; i++) {
        Directory_free(self->items[i]);
    }
    Array_free(self);
}

// --- Recent Implementation ---
// Note: hasEmu is a dependency that will be moved later.
// For now, we declare it here to make this file self-contained.
// static int hasEmu(char* emu_name);

Recent* Recent_new(char* path, char* alias) {
    Recent* self = malloc(sizeof(Recent));

    char sd_path[256];
    sprintf(sd_path, "%s%s", SDCARD_PATH, path);

    char emu_name[256];
    getEmuName(sd_path, emu_name);

    self->path = strdup(path);
    self->alias = alias ? strdup(alias) : NULL;
    self->available = hasEmu(emu_name);
    return self;
}

void Recent_free(Recent* self) {
    free(self->path);
    if (self->alias) free(self->alias);
    free(self);
}

int RecentArray_indexOf(Array* self, char* str) {
    for (int i = 0; i < self->count; i++) {
        Recent* item = self->items[i];
        if (exactMatch(item->path, str)) return i;
    }
    return -1;
}

void RecentArray_free(Array* self) {
    for (int i = 0; i < self->count; i++) {
        Recent_free(self->items[i]);
    }
    Array_free(self);
}
